from __future__ import annotations

import copy
import torch

from abc import ABC, abstractmethod
from loguru import logger

from typing import TYPE_CHECKING

from src.circuits.layer_spec import LayerSpec

if TYPE_CHECKING:
    from src.circuits.circuit import CircuitGenome


DECODING_OPTIONS = ["clipped", "linear"]


def initialize_decoder(
    target: str, decoding_str: str, n_inputs: int, n_outputs: int
) -> Decoder:
    """
    Given the target system (e.g., pennylane or qiskit) create a
    new decoder to perform decodings from classical to quantum
    which will set the input parameter and input gate for each wire.

    Args:
        target: the target system (pennylane or qiskit)
        decoding_str: a string representation of the decoder
            to be created
        n_outputs: how many output values are required for the loss
            function, which the decoder will perform some operation
            to reduce its input tensor to.

    Raises:
        ValueError: If the decoder is unknown, or a clipped decoder is requested
            with ``n_outputs > n_inputs`` (it can only keep a prefix of its
            input, so it cannot produce more outputs than it receives).
    """

    logger.info(
        f"creating {decoding_str} decoder with n_inputs: {n_inputs} and n_outputs: {n_outputs}"
    )

    decoder = None

    if decoding_str == "clipped":
        # Validate before constructing: a clipped decoder keeps only the first
        # n_outputs values, so it cannot expand its input.
        if n_outputs > n_inputs:
            raise ValueError(
                f"ClippedDecoder requires n_outputs <= n_inputs, but got "
                f"n_outputs={n_outputs} and n_inputs={n_inputs}. It keeps only "
                f"the first n_outputs values, so it cannot produce more outputs "
                f"than it receives; reduce n_outputs (or use a linear decoder to "
                f"expand the size)."
            )
        decoder = ClippedDecoder(n_inputs, n_outputs)

    elif decoding_str == "linear":
        decoder = LinearDecoder(n_inputs, n_outputs)

    else:
        raise ValueError(f"Unknown decoder={decoding_str} for target={target}")

    return decoder


class Decoder(ABC):
    def __init__(self, n_inputs: int, n_outputs: int):
        """
        Base constructor for a decoder, as each will need to know how many
        outputs it needs to decode to.

        Args:
            n_inputs: how many input values will be passed into the decoder,
                which we need to initialize more complex decoders.
            n_outputs: how many output values are required for the loss
                function, which the decoder will perform some operation
                to reduce its input tensor to.
        """
        self.n_inputs = n_inputs
        self.n_outputs = n_outputs

    @abstractmethod
    def __call__(self, inputs: torch.Tensor, genome: CircuitGenome):
        """
        Given the torch tensor of input values and the circuit genome,
        this should set the input qubits of the quantum circuit model
        being used for pytorch forward/backward passes.

        Args:
            inputs: the x (input) tensor for a sample
            genome: the circuit genome whose quantum circuit
                inputs are being set
        """
        pass

    def to_dict(self) -> dict[str, any]:
        """
        This converts the decoder to a dict so it can be written as
        JSON for passing via MPI message passing, or saved to disk.

        The default is just to write the class name and then arguments
        used to construct the decoder in the args entry. This allows
        us to use a standard method with reflection for construcing
        the decoders backfrom JSON.
        """

        response_dict = {
            "class": type(self).__name__,
            "args": {
                "n_inputs": self.n_inputs,
                "n_outputs": self.n_outputs,
            },
        }

        # for Decoders that are pytorch modules, also save
        # their parameters (so we don't need to reimplement
        # this for each of them).
        if isinstance(self, torch.nn.Module):
            state_dict = self.state_dict()

            serialized_dict = {
                name: tensor.cpu().numpy().tolist()
                for name, tensor in state_dict.items()
            }

            """
            logger.debug("serialized nn.Module tensor dict:")
            logger.debug(json.dumps(serialized_dict, indent=4))
            """

            response_dict["args"]["state_dict"] = serialized_dict

        # logger.debug("decoder json is:")
        # logger.debug(json.dumps(response_dict, ensure_ascii=False, indent=4))

        return response_dict

    @classmethod
    def from_dict(cls, serialized: dict[str, any]) -> Decoder:
        """
        Given a dict created from the serialized JSON generated by the
        `to_dict` method, create the class with the given args from
        the JSON.

        Args:
            serialized: is the dict created from the serialized JSON.

        Returns:
            A constructed Decoder object created from the given JSON.
        """

        # remove the module parameters so we can call the default
        # constructor
        serialized_state_dict = None
        if "state_dict" in serialized["args"].keys():
            serialized_state_dict = serialized["args"].pop("state_dict")

        class_init = globals()[serialized["class"]]
        class_object = class_init(**serialized["args"])

        if isinstance(class_object, torch.nn.Module):
            # convert the JSON values back into tensors
            state_dict = {
                name: torch.tensor(list_data)
                for name, list_data in serialized_state_dict.items()
            }

            # set the module's parameter tensors
            class_object.load_state_dict(state_dict)

        return class_object

    def copy(self) -> Decoder:
        """
        Creates a copy of the decoder (if needed) so modifying a genome's
        decoder does not effect the one of its parent.
        """
        pass

    def describe_layers(self) -> list[LayerSpec]:
        """Describes this decoder as an ordered list of drawable layers.

        Used by the architecture diagram compositor
        (:func:`src.utils.draw_hybrid_model.draw_hybrid_model`). The base implementation
        returns a single generic block; subclasses override this to expose
        their real layer structure.

        Returns:
            A list of :class:`~src.circuits.layer_spec.LayerSpec` describing the
            decoder's layers in input-to-output order.
        """
        return [
            LayerSpec(
                kind="block",
                label=type(self).__name__,
                in_shape=(self.n_inputs,),
                out_shape=(self.n_outputs,),
            )
        ]


class ClippedDecoder(Decoder):
    def __call__(self, inputs: torch.Tensor, genome: CircuitGenome):
        """
        Returns the first N values, for the decoding discarding
        the rest, where N is the expected number of outputs
        for the loss function.

        The values are returned unmodified (no sum-to-1 rescaling): every
        downstream consumer re-applies its own normalization -- classification
        uses ``CrossEntropyLoss`` (an internal ``log_softmax``) and the discrete
        reinforcement-learning policies use ``Categorical(logits=...)`` (an
        internal softmax), while the continuous policies read per-dimension mean
        and log-std slots directly -- so none of them require a normalized input.

        Args:
            inputs: the z (output) tensor from a quantum circuit.
            genome: the circuit genome whose quantum circuit
                inputs are being set

        Returns:
            The leading ``self.n_outputs`` values of ``inputs`` along the last
            dimension, unmodified.
        """

        return inputs[..., : self.n_outputs]

    def describe_layers(self) -> list[LayerSpec]:
        """Describes the clipped decoder as a single pass-through block.

        Returns:
            A one-element list with a ``"passthrough"`` :class:`LayerSpec` (it
            keeps the leading ``n_outputs`` values without trainable weights).
        """
        return [
            LayerSpec(
                kind="passthrough",
                label="Clip",
                in_shape=(self.n_inputs,),
                out_shape=(self.n_outputs,),
            )
        ]

    def copy(self) -> Decoder:
        return self


class LinearDecoder(torch.nn.Module, Decoder):
    def __init__(self, n_inputs: int, n_outputs: int):
        """
        Base constructor for a decoder, as each will need to know how many
        outputs it needs to decode to.

        Args:
            n_inputs: how many inputs will be passed to the decoder, which
                is typically the number of output qubits times 2.
            n_outputs: how many output values are required for the loss
                function, which the decoder will perform some operation
                to reduce its input tensor to.
        """
        # initialize both superclasses
        torch.nn.Module.__init__(self)
        Decoder.__init__(self, n_inputs, n_outputs)

        logger.debug(
            f"creating decoder with n_inputs: {n_inputs} and n_outputs: {n_outputs}"
        )

        self.layer = torch.nn.Linear(self.n_inputs, self.n_outputs)

        # initalize the layer weights randomly
        torch.nn.init.xavier_uniform_(self.layer.weight)
        torch.nn.init.zeros_(self.layer.bias)

    def __call__(self, inputs: torch.Tensor, genome: CircuitGenome):
        """
        Returns the first N values, for the decoding discarding
        the rest, where N is the expected number of outputs
        for the loss function.

        Args:
            inputs: the z (output) tensor from a quantum circuit.
            genome: the circuit genome whose quantum circuit
                inputs are being set
        """

        """
        print(f"forward on linear, inputs: {inputs}, type: {inputs.dtype}")
        print(f"weights: {self.layer.weight}, type: {self.layer.weight.dtype}")
        print(f"biases: {self.layer.bias}, type: {self.layer.bias.dtype}")
        """

        # linear layer requires float32 values
        return self.layer(inputs.float())

    def describe_layers(self) -> list[LayerSpec]:
        """Describes the linear decoder as a single fully connected layer.

        Returns:
            A one-element list with an ``"fc"`` :class:`LayerSpec` mapping
            ``n_inputs`` -> ``n_outputs``.
        """
        return [
            LayerSpec(
                kind="fc",
                label="Linear",
                in_shape=(self.n_inputs,),
                out_shape=(self.n_outputs,),
            )
        ]

    def copy(self) -> Decoder:
        """
        Returns:
            A deepcopy of this decoder so if it can be reused by child
            genomes without modifying the parents decoder.
        """
        return copy.deepcopy(self)
