from __future__ import annotations

import random
import torch
from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    from src.circuits.circuit import CircuitGenome


def gate_dropout(
    gates: list[Any],
    dropout_rate: float,
) -> set[int]:
    """Samples uniform gate dropout.

    Args:
        gates: Gates in the quantum circuit.
        dropout_rate: Probability of dropping each enabled gate.

    Returns:
        Innovation numbers of gates selected for dropout.
    """
    _validate_dropout_rate(dropout_rate)

    return {
        gate.innovation_number
        for gate in gates
        if gate.enabled and random.random() < dropout_rate
    }


def rotation_dropout(
    gates: list[Any],
    dropout_rate: float,
) -> set[int]:
    """Samples dropout over parameterized gates.

    Args:
        gates: Gates in the quantum circuit.
        dropout_rate: Probability of dropping each enabled gate.

    Returns:
        Innovation numbers of gates selected for dropout.
    """
    _validate_dropout_rate(dropout_rate)

    rotation_gates = {
        "rx",
        "ry",
        "rz",
        "u",
    }

    return {
        gate.innovation_number
        for gate in gates
        if (
            gate.enabled
            and gate.method_name.lower() in rotation_gates
            and random.random() < dropout_rate
        )
    }


def entangling_dropout(
    gates: list[Any],
    dropout_rate: float,
) -> set[int]:
    """Samples dropout over multi-qubit gates.

    Args:
        gates: Gates in the quantum circuit.
        dropout_rate: Probability of dropping each enabled gate.

    Returns:
        Innovation numbers of gates selected for dropout.
    """
    _validate_dropout_rate(dropout_rate)

    return {
        gate.innovation_number
        for gate in gates
        if (gate.enabled and len(gate.qubits) > 1 and random.random() < dropout_rate)
    }


def apply_qubit_readout_dropout(
    quantum_output: torch.Tensor,
    output_qubits: list[tuple[str, int]],
    dropped_qubits: set[tuple[str, int]],
    output_mode: str,
) -> torch.Tensor:
    """Removes dropped-qubit information from the quantum readout.

    For expectation-value outputs, the corresponding readout is set to
    zero. For probability outputs, the dropped qubit is marginalized and
    replaced by a uniform distribution while preserving the original
    output dimensionality.

    Args:
        quantum_output: Output generated by the quantum circuit.
        output_qubits: Ordered qubits used for quantum measurement.
        dropped_qubits: Qubits selected by qubit dropout.
        output_mode: Quantum output mode, e.g. ``expval`` or ``probs``.

    Returns:
        Quantum output with dropped-qubit information removed.
    """
    if not dropped_qubits:
        return quantum_output

    dropped_output_qubits = {
        qubit for qubit in dropped_qubits if qubit in output_qubits
    }

    if not dropped_output_qubits:
        return quantum_output

    if output_mode == "expval":
        output = quantum_output.clone()

        for index, qubit in enumerate(output_qubits):
            if qubit in dropped_output_qubits:
                output[..., index] = 0.0

        return output

    if output_mode == "probs":
        return _apply_probability_qubit_dropout(
            quantum_output,
            output_qubits,
            dropped_output_qubits,
        )

    return quantum_output


def _apply_probability_qubit_dropout(
    probabilities: torch.Tensor,
    output_qubits: list[tuple[str, int]],
    dropped_qubits: set[tuple[str, int]],
) -> torch.Tensor:
    """Makes dropped qubits uniform in a joint probability distribution.

    Args:
        probabilities: Probabilities for all the quantum states.
        output_qubits: Ordered qubits used for quantum measurement.
        dropped_qubits: Qubits selected by qubit dropout.

    Returns:
        Marginalized probability distribution
    """
    n_qubits = len(output_qubits)

    expected_outputs = 2**n_qubits

    if probabilities.shape[-1] != expected_outputs:
        raise ValueError(
            "Probability output dimension does not match output qubits: "
            f"expected {expected_outputs}, "
            f"received {probabilities.shape[-1]}."
        )

    original_shape = probabilities.shape

    # [batch, 2**n]
    #
    # becomes
    #
    # [batch, 2, 2, ..., 2]
    probs = probabilities.reshape(
        *original_shape[:-1],
        *([2] * n_qubits),
    )

    # Number of dimensions before the qubit dimensions.
    leading_dims = probabilities.ndim - 1

    for qubit_index, qubit in enumerate(output_qubits):
        if qubit not in dropped_qubits:
            continue

        axis = leading_dims + qubit_index

        # Remove information associated with the dropped qubit.
        marginal = probs.sum(
            dim=axis,
            keepdim=True,
        )

        # Reinsert the dropped qubit as a uniform variable:
        #
        # P(q=0) = P(q=1) = 0.5
        probs = torch.cat(
            [
                marginal / 2.0,
                marginal / 2.0,
            ],
            dim=axis,
        )

    return probs.reshape(original_shape)


def qubit_dropout(
    qubits: list[tuple[str, int]],
    dropout_rate: float,
) -> set[tuple[str, int]]:
    """Samples quantum dropout at the qubit level.

    Each candidate qubit is independently selected for dropout. Any
    evolved gate acting on a dropped qubit is skipped during the current
    forward pass.

    Input encoding and output measurement are not removed; only evolved
    gates are affected.

    Args:
        qubits: The list of genome qubits.
        dropout_rate: Probability of dropping each enabled gate.

    Returns:
        Innovation numbers of gates selected for dropout.
    """
    _validate_dropout_rate(dropout_rate)

    return {
        qubit
        for qubit in qubits
        # if qubit not in genome.output_qubits
        if random.random() < dropout_rate
    }


def innovation_dropout(
    gates: list[Any],
    dropout_rate: float,
    innovation_strength: float = 0.5,
) -> set[int]:
    """Samples innovation-aware gate dropout.

    Newer innovations receive a larger dropout probability than
    older innovations.

    Args:
        gates: Gates in the quantum circuit.
        dropout_rate: Mean target dropout probability.
        innovation_strength: Strength of the innovation-rank bias.

    Returns:
        Innovation numbers of gates selected for dropout.
    """
    _validate_dropout_rate(dropout_rate)

    if not 0.0 <= innovation_strength <= 1.0:
        raise ValueError("innovation_strength must be in [0, 1].")

    enabled_gates = sorted(
        [gate for gate in gates if gate.enabled],
        key=lambda gate: gate.innovation_number,
    )

    n_gates = len(enabled_gates)

    if n_gates == 0:
        return set()

    dropped = set()

    for rank, gate in enumerate(enabled_gates):
        normalized_rank = 0.5 if n_gates == 1 else rank / (n_gates - 1)

        probability = dropout_rate * (
            1.0 + innovation_strength * (2.0 * normalized_rank - 1.0)
        )

        probability = min(max(probability, 0.0), 1.0)

        if random.random() < probability:
            dropped.add(gate.innovation_number)

    return dropped


def _validate_dropout_rate(dropout_rate: float) -> None:
    """Validates a dropout probability."""
    if not 0.0 <= dropout_rate <= 1.0:
        raise ValueError("dropout_rate must be in [0, 1], " f"received {dropout_rate}.")


def sample_quantum_dropout(genome: CircuitGenome) -> None:
    """Samples the configured quantum dropout for a genome, in place.

    Reads ``quantum_dropout_type`` and ``quantum_dropout_rate`` (and, for the
    ``"innovation"`` type, ``quantum_dropout_innovation_strength``) from
    ``genome.hyperparameters``, and populates the genome's dropout state
    (``dropout_gate_innovations`` for gate-level dropout types, or
    ``dropout_qubits`` for ``"qubit"`` dropout). Any previously sampled dropout
    is cleared first, so calling this with a zero rate or a ``"none"`` type
    simply leaves the genome with no dropout.

    This is the single source of truth for quantum dropout shared by the
    supervised and reinforcement-learning trainers, so both trainers apply
    dropout by simply calling this function. Gate-level dropout is read directly
    from the genome during the forward pass; for ``"qubit"`` dropout this also
    mirrors ``genome.dropout_qubits`` onto ``genome.hybrid_model`` so the
    forward pass masks those qubits. Requires ``genome.initialize_model`` to
    have been called when qubit dropout is active.

    Args:
        genome: The genome whose dropout state is (re)sampled in place.

    Returns:
        None. Mutates ``genome.dropout_gate_innovations`` /
        ``genome.dropout_qubits`` (and, for qubit dropout, the hybrid model's
        ``dropout_qubits``).

    Raises:
        ValueError: If ``quantum_dropout_type`` is not one of the supported
            values.
    """

    genome.clear_quantum_dropout()

    dropout_type = genome.hyperparameters.get("quantum_dropout_type", "none")
    dropout_rate = float(genome.hyperparameters.get("quantum_dropout_rate", 0.0))

    if dropout_rate == 0.0 or dropout_type == "none":
        return

    if dropout_type == "gate":
        genome.dropout_gate_innovations = gate_dropout(genome.gates, dropout_rate)

    elif dropout_type == "rotation":
        genome.dropout_gate_innovations = rotation_dropout(genome.gates, dropout_rate)

    elif dropout_type == "entangling":
        genome.dropout_gate_innovations = entangling_dropout(genome.gates, dropout_rate)

    elif dropout_type == "qubit":
        genome.dropout_qubits = qubit_dropout(genome.qubits, dropout_rate)

    elif dropout_type == "innovation":
        genome.dropout_gate_innovations = innovation_dropout(
            genome.gates,
            dropout_rate,
            innovation_strength=float(
                genome.hyperparameters.get(
                    "quantum_dropout_innovation_strength",
                    0.5,
                )
            ),
        )

    else:
        raise ValueError(f"Unknown quantum dropout type: {dropout_type}")

    # Qubit dropout is enforced by the hybrid model's forward pass, so mirror
    # the sampled qubits (and the output configuration it needs to mask them)
    # onto the model. Gate-level dropout types are read directly from the genome
    # and need no mirroring.
    if genome.dropout_qubits:
        genome.hybrid_model.dropout_qubits = genome.dropout_qubits
        genome.hybrid_model.output_qubits = genome.output_qubits
        genome.hybrid_model.quantum_output_mode = genome.hyperparameters[
            "quantum_output_mode"
        ]
